spring:
  profiles:
    active: chaos-monkey

chaos:
  monkey:
    enabled: false
    watcher:
      service: false
      controller: false
      repository: false
      restController: false
    assaults:
      level: 3
      latencyActive: true
      latencyRangeStart: 1000
      latencyRangeEnd: 4000
      exceptionsActive: true
